# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

group :assets do
  gem 'bootstrap-sass', '~> 2.3.2.2'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'sass-rails', '~> 5.0.8'
  gem 'uglifier', '>= 2.7'
end

gem 'attr_encrypted', '~> 3.0.0'
gem 'auth0', '4.1.0'
gem 'awesome_print'
gem 'aws-sdk-s3'
gem 'aws-sdk-core'
gem 'avro', '~> 1.8.2', source: 'https://rubygems.org'
gem 'business_time'
gem 'chronic'
gem 'countries'
gem 'delayed_job_active_record'
gem 'devise', '~> 4.2', '>= 4.2.1'
gem 'dotenv'
gem 'draper', '~> 2.0.0'
gem 'faraday'
gem 'faraday_middleware'
gem 'flip'
gem 'font-awesome-rails', '>= 4.3.0.0'
gem 'formatador'
gem 'haml', '~> 4.0'
gem 'hashie', '~> 3.0'
gem 'holidays'
gem 'honeybadger', '~> 3.3'
gem 'httparty'
gem 'hutch'
gem 'jquery-rails', '~> 3.1.5'
gem 'json-schema', '~> 2.8.0'
gem 'mime-types', '2.99.3'
gem 'monetize'
gem 'money', '~> 6.8.1'
gem 'mustache'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.11.4'
gem 'pkg-config', '~> 1.1'
gem 'pg'
gem 'premailer-rails', '>= 1.8.1'
gem 'rack-oauth2'
gem 'rack-rewrite'
gem 'rack-cors', require: 'rack/cors'
gem 'rubocop', '~> 0.49.1', require: false
gem 'rails', '~> 4.2.11'
gem 'rails_12factor', group: [:uat]
gem 'react_on_rails', '~> 9.0.3'
gem 'ruby-duration', '~> 3.2.0'
gem 'simple_form', '~> 4.0', '>= 4.0.0'
gem 'unicorn', require: false
gem 'virtus', '~> 0.5.5'
gem 'webpacker', '~> 3.0', '>= 3.0.2'
gem 'whenever', '~> 0.9.4', require: false
gem 'will_paginate', '~> 3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bower-rails', '~> 0.7.0'
  gem 'letter_opener'
  gem 'parallel_tests'
  gem 'quiet_assets'
  gem 'foreman'
end

group :test, :development do
  gem 'launchy'
  gem 'oauth2'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-stack_explorer'
  gem 'rspec-its'
  gem 'rspec-rails', '>= 3.5.0'
  gem 'zeus'
  gem 'benchmark-memory'
  gem 'factory_girl'
  gem 'guard'
  gem 'guard-rspec'
end

group :test do
  gem 'capybara', '~> 2.4', '>= 2.4.0'
  gem 'codeclimate-test-reporter', group: :test, require: nil
  gem 'poltergeist', '>= 1.14.0'
  gem 'rspec_junit_formatter'
  gem 'shoulda-matchers'
  gem 'simplecov', '~> 0.9'
  gem 'timecop'
  gem 'webmock', require: false
end
